### ISSUE TITLE
FrontMatter options

### ISSUE THREAD

**Issue by Yago** [frontend/generator-toolbox#33]
- preview background color
- wrapper

**Comment by tonifisler** [comment]
## Suggestions for the `wrapper` option

``` yml
# 1. we provide the whole markup with a component token: `#{component}` or similar
wrapper: <div class="my-class"><div class="my-other-class">#{component}</div></div>

# 2. we add some Emmet power
wrapper: .my-class>.my-other-class

# 3. we generate divs from a list of classes
wrappers:
  - my-class
  - my-other-class

# 4. we only add the option as a class to the `.styleguide-item-preview` element
wrapper: my-class
```

cc @Yago @WengerK
